#!/bin/bash
# Install script created by dmc-access-mgr
progname=$(basename $0)
opt_f='no'
opt_d='no'

usage() {
    cat << _EOF

"$progname" print the version string

Usage $0 [OPTIONS]

 -d    uninstall the existing installation first and exit. Run again to install.
 -f    force the installation when the machine cannot be identified as
       a gateway or a missing software package or missing server process is detected.

_EOF
}

if [[ "$EUID" -ne 0 ]]; then
    >&2 echo "error: This installer needs to be run with superuser privileges."
    >&2 echo ""
    >&2 echo "           sudo $0"
    >&2 echo ""
    exit 1
fi

while getopts dfh c ; do
    case $c in
        d) opt_d='yes' ;;
        f) opt_f='yes' ;;
        h) usage ; exit 0 ;;
        \?) usage ; >&2 echo"unknown option: $c" ; exit 1 ;;
    esac
done

interfaces=$(ip link | awk '/^[0-9]*: /{print substr($2, 1, length($2)-1)}')

ifcnt=0
cfg=0
for interface in $interfaces ; do
    case $interface in
	enp?s0)   ((ifcnt++)) ;;
	lanbr0)   ((cfg++))   ;;
	tun0)     ((cfg++))   ;;
	gretap1*) ((cfg++))   ;;
    esac
done

if [ $ifcnt -lt 4 -a $opt_f == 'no' ] ; then
    >&2 echo "error: Cannot install because this machine does not seem to be a remote gateway."
    >&2 echo "       Use -f option to force gateway install anyway."
    exit 1
fi

if [ $cfg -gt 2 -a $opt_d == 'no' ] ; then
    >&2 echo "error: Cannot install because this gateway is already installed."
    >&2 echo "       Use -d option to uninstall gateway first."
    exit 1
fi

if [ $opt_d == 'yes' ] ; then
    echo "DMC gateway uninstall is ready to begin."
else
    echo "DMC gateway installation is ready to begin."
fi
read -n1 -r -p "Press any key to continue..."

if [ $opt_d == 'yes' ] ; then
    echo "Uninstalling gateway"
    for yaml in /etc/netplan/*.yaml ; do
        case $yaml in
            00*) ;;
            *) rm $yaml ;;
        esac
    done
    for openvpnconf in /etc/openvpn/*.conf; do
        if [ -e $openvpnconf ] ; then
            service=$(basename -s .conf ${openvpnconf}).service
            systemctl stop $service
            systemctl disable $service
            rm $openvpnconf
        fi
    done
    ip link del lanbr0
    ip link del gretap1
    systemctl stop snmpd
    if [ -f /etc/snmp/snmpd.conf.bak ] ; then
        mv /etc/snmp/snmpd.conf.bak /etc/snmp/snmpd.conf
    fi
    systemctl start snmpd
else
    sed '0,/^__EOF__$/d' $0 | tar xz -C /
    if [ -f /etc/netplan/01-network-manager-all.yaml ] ; then
        rm /etc/netplan/01-network-manager-all.yaml
    fi

    if [ ! -e '/usr/sbin/sshd' ] ; then
        >&2 echo "warning: ssh server is not installed: trying to install now"
        apt -y install openssh-server
        if [ ! -e '/usr/sbin/sshd' ] ; then
            >&2 echo "error: unable to install ssh server please resolve before proceeding"
            >&2 echo "    sudo apt install openssh-server"
            [ $opt_f == 'yes' ] || exit 1
        fi
    fi
    ssh=$(systemctl is-active ssh)
    if [ "$ssh" != 'active' ] ; then
        >&2 echo "warning: ssh server is not running: trying to activate it "
        systemctl enable ssh
        systemctl start ssh
        ssh=$(systemctl is-active ssh)
        if [ "$ssh" != 'active' ] ; then
            >&2 echo "error: unable to start ssh server please resolve before proceeding"
            >&2 echo "    sudo systemctl start ssh"
            [ $opt_f == 'yes' ] || exit 1
        fi
    fi
    if [ ! -e '/usr/sbin/snmpd' -o ! -e '/usr/bin/net-snmp-create-v3-user' ] ; then
        >&2 echo "warning: SNMP is not installed: trying to install now"
        apt install snmpd snmp libsnmp-dev
        if [ ! -e '/usr/sbin/snmpd' -o ! -e '/usr/bin/net-snmp-create-v3-user' ] ; then
            >&2 echo "error: unable to install SNMP server and tools please resolve before proceeding"
            >&2 echo "    sudo apt install snmpd snmp libsnmp-dev"
            [ $opt_f == 'yes' ] || exit 1
        fi
    fi
    snmpd=$(systemctl is-active snmpd)
    if [ "$snmpd" != 'active' ] ; then
        >&2 echo "warning: SNMP server is not running: trying to activate it "
        systemctl enable snmpd
        systemctl start snmpd
        snmpd=$(systemctl is-active snmpd)
        if [ "$snmpd" != 'active' ] ; then
            >&2 echo "error: snmpd server is not installed: try: "
            >&2 echo "    sudo systemctl enable snmpd"
            >&2 echo "    sudo systemctl start snmpd"
            [ $opt_f == 'yes' ] || exit 1
        fi
    fi
    systemctl stop snmpd
    sed -i.bak 's/^sysLocation.*$/sysLocation Dali Management VPN Gateway/;s/^sysContact.*$/sysContact Dali <support@daliwireless.com>/;s/^agentaddress.*$/agentaddress udp:161,udp6:[::1]:161/' /etc/snmp/snmpd.conf
    net-snmp-create-v3-user -ro -A "${SNMP_PASSWORD}" -a MD5 -X "${SNMP_PASSWORD}" -x DES "${SNMP_USER}"
    systemctl start snmpd
fi

systemctl daemon-reload
systemctl restart openvpn
netplan generate
netplan apply

exit 0
__EOF__
